import type { EvalResult } from '../eval.js';

const VERDICT_BADGE = {
  helps: ':white_check_mark: HELPS',
  placebo: ':heavy_minus_sign: PLACEBO',
  harms: ':x: HARMS'
} as const;

function pct(n: number): string {
  return `${(n * 100).toFixed(1)}%`;
}

function pp(n: number): string {
  return `${n >= 0 ? '+' : ''}${n.toFixed(1)} pp`;
}

function excerpt(prompt: string, max = 80): string {
  const single = prompt.replace(/\s+/g, ' ').trim();
  return single.length > max ? `${single.slice(0, max - 1).trimEnd()}…` : single;
}

// A literal `|` would split a GFM table cell, so escape it.
function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

/**
 * Formats an evaluation result as a GitHub-Flavored Markdown report, ready to
 * redirect into `$GITHUB_STEP_SUMMARY` or paste as a pull request comment.
 */
export function formatMarkdownReport(result: EvalResult): string {
  const { skill, config, result: outcome } = result;
  const [ciLow, ciHigh] = outcome.ci_pp;

  const lines: string[] = [
    `# Skillcheck Evaluation: ${skill.name}`,
    '',
    `## ${VERDICT_BADGE[outcome.verdict]}`,
    '',
    `**Satisfaction:** ${outcome.satisfaction.toFixed(1)}/100 · **Effect size:** ${pp(outcome.effect_pp)}`,
    '',
    '## Statistical Summary',
    '',
    '| Metric | Value |',
    '|---|---|',
    `| Observed effect | ${pp(outcome.effect_pp)} |`,
    `| 95% CI | [${ciLow.toFixed(1)}, ${ciHigh.toFixed(1)}] |`,
    `| With-skill pass rate | ${pct(outcome.with_skill_pass)} |`,
    `| Without-skill pass rate | ${pct(outcome.no_skill_pass)} |`,
    `| Token overhead | +${outcome.token_overhead} tokens |`,
    ''
  ];

  if (result.tasks.length > 0) {
    lines.push(
      '## Task Breakdown',
      '',
      '| Task | Prompt | With Skill | Without Skill | Delta |',
      '|---|---|---|---|---|'
    );
    for (const task of result.tasks) {
      const delta = (task.with_skill_pass_rate - task.no_skill_pass_rate) * 100;
      lines.push(
        `| ${escapeCell(task.id)} | ${escapeCell(excerpt(task.prompt))} | ${pct(task.with_skill_pass_rate)} | ${pct(task.no_skill_pass_rate)} | ${pp(delta)} |`
      );
    }
    lines.push('');
  }

  lines.push(
    '## Run Metadata',
    '',
    `- **Models:** runner \`${config.runner_model}\`, grader \`${config.grader_model}\`, generator \`${config.generator_model}\``,
    `- **Trials:** ${config.trials} per task and arm · **Tasks:** ${config.tasks}`,
    `- **Commit:** \`${skill.commit_hash}\` · **Date:** ${result.run_date}`,
    '',
    '<sub>Generated by [Skillcheck](https://github.com/sx4im/skillcheck)</sub>'
  );

  return lines.join('\n');
}
